linters-settings:
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 42
  cyclop:
    max-complexity: 42
  maligned:
    suggest-new: true
  dupl:
    threshold: 200
  revive:
    rules:
    - name: var-naming
      severity: warning
      disabled: true

linters:
  enable-all: true
  disable:
    - dupl
    - exhaustive
    - exhaustivestruct
    - funlen
    - gci
    - gochecknoglobals
    - gocognit
    - goconst
    - gocyclo
    - godot
    - goerr113
    - gofumpt
    - gomnd
    - lll
    - nestif
    - nlreturn
    - wrapcheck
    - wsl
    - nakedret
    - paralleltest
    - testpackage
    - nonamedreturns
    - nosnakecase
    - varnamelen
    - staticcheck
    - exhaustruct
    - forcetypeassert
