linters-settings:
  govet:
    shadow: true
  gocyclo:
    min-complexity: 42
  cyclop:
    max-complexity: 42
  dupl:
    threshold: 200
  revive:
    rules:
    - name: var-naming
      severity: warning
      disabled: true
linters:
  enable-all: true
  disable:
    - ireturn
    - dupl
    - exhaustive
    - funlen
    - gci
    - gochecknoglobals
    - gocognit
    - goconst
    - gocyclo
    - godot
    - lll
    - nestif
    - nlreturn
    - wrapcheck
    - wsl
    - nakedret
    - paralleltest
    - testpackage
    - varnamelen
    - exhaustruct
    - nonamedreturns
    - forcetypeassert
    - depguard
    - mnd
    - inamedparam
    - asasalint
    - err113 # maybe tmp disable
    - tagliatelle
    - testifylint
    - typecheck
    - recvcheck # maybe tmp disable
    - tenv # deprecated
issues:
  exclude:
    - "tag is not aligned, should be:" # this is harder to read
