# Copyright 2019 HAProxy Technologies LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http:#www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    binary: haproxy-ingress-controller
    id: my-build
    ldflags:
      - -X "main.GitRepo={{.GitURL}}"
      - -X "main.GitTag={{.Tag}}"
      - -X "main.GitCommit={{.ShortCommit}}"
      - -X "main.BuildTime={{.Date}}"
    goos:
      - linux
      - darwin
      - freebsd
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
      - ppc64le
      - s390x
archives:
  - name_template: |-
      {{- $prettyOS := .Os -}}
      {{- if eq $prettyOS "darwin" -}}
      	{{- $prettyOS = "Darwin" -}}
      {{- else if eq $prettyOS "linux" -}}
      	{{- $prettyOS = "Linux" -}}
      {{- else if eq $prettyOS "freebsd" -}}
      	{{- $prettyOS = "FreeBSD" -}}
      {{- end -}}

      {{- $prettyArch := .Arch -}}
      {{- if eq $prettyArch "386" -}}
      	{{- $prettyArch = "i386" -}}
      {{- else if eq $prettyArch "amd64" -}}
      	{{- $prettyArch = "x86_64" -}}
      {{- end -}}
      {{.Binary}}_{{.Version}}_{{$prettyOS}}_{{$prettyArch}}
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
release:
  draft: false
  name_template: "HAProxy Ingress Controller v{{.Version}}"
