// Copyright 2019 HAProxy Technologies LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
package main

import (
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"gopkg.in/yaml.v3"
)

func twoShardJobSet() []JobSet {
	return []JobSet{{
		Name:      "e2e_k8s",
		Stage:     "e2e_k8s",
		When:      "mr_or_push",
		Splits:    []Split{{Tag: "e2e_sequential", Mode: "sequential", Shards: 2}},
		Variables: map[string]string{"K8S_VERSION": "v1.34.0"},
	}}
}

func fourTests() []TestCase {
	return []TestCase{
		{Tag: "e2e_sequential", Package: "./deploy/tests/e2e/cors", Name: "TestCorsSuite"},
		{Tag: "e2e_sequential", Package: "./deploy/tests/e2e/crd", Name: "TestGlobalSuite"},
		{Tag: "e2e_sequential", Package: "./deploy/tests/e2e/crd-tcp", Name: "TestTCPSuite"},
		{Tag: "e2e_sequential", Package: "./deploy/tests/e2e/tls-auth", Name: "TestTLSAuthSuite"},
		{Tag: "e2e_parallel", Package: "./deploy/tests/e2e/cookie-persistence", Name: "TestCookieSuite"},
	}
}

func TestBuildPipelineMakesOneJobPerShardAndPinsInOrder(t *testing.T) {
	p := buildPipeline(twoShardJobSet(), fourTests(), []string{"go-r1", "go-r2"})
	require.Len(t, p.Legs, 2)
	assert.Equal(t, []string{"e2e_k8s"}, p.Stages)
	assert.Equal(t, "e2e_k8s:sequential-1", p.Legs[0].Name)
	assert.Equal(t, "go-r1", p.Legs[0].Tag)
	assert.Equal(t, "e2e_k8s:sequential-2", p.Legs[1].Name)
	assert.Equal(t, "go-r2", p.Legs[1].Tag)
}

// TestBuildPipelineDealsEveryTestExactlyOnce is the safety net for the split:
// losing or duplicating a test would silently change what the pipeline covers.
func TestBuildPipelineDealsEveryTestExactlyOnce(t *testing.T) {
	p := buildPipeline(twoShardJobSet(), fourTests(), nil)

	seen := []string{}
	for _, l := range p.Legs {
		for _, v := range l.Variables {
			if v.Name == "E2E_TESTS" {
				seen = append(seen, strings.Fields(v.Value)...)
			}
		}
	}
	assert.ElementsMatch(t, []string{
		"./deploy/tests/e2e/cors:TestCorsSuite",
		"./deploy/tests/e2e/crd:TestGlobalSuite",
		"./deploy/tests/e2e/crd-tcp:TestTCPSuite",
		"./deploy/tests/e2e/tls-auth:TestTLSAuthSuite",
	}, seen)
}

func TestBuildPipelineSkipsASplitWithNoMatchingTests(t *testing.T) {
	jobs := []JobSet{{
		Name:   "e2e_k8s",
		Stage:  "e2e_k8s",
		Splits: []Split{{Tag: "e2e_absent", Shards: 2}},
	}}
	p := buildPipeline(jobs, fourTests(), nil)
	assert.Empty(t, p.Legs)
	assert.Empty(t, p.Stages)
}

func TestRenderPinsEachShardToItsRunner(t *testing.T) {
	out, err := render(buildPipeline(twoShardJobSet(), fourTests(), []string{"go-r1", "go-r2"}))
	require.NoError(t, err)

	expected := `# Generated by cmd/gitlab-e2e-jobs. Do not edit.
include:
  - local: .gitlab/variables.yml
  - local: .gitlab/.templates.yml

stages:
  - e2e_k8s

"e2e_k8s:sequential-1":
  extends: .kind_deployment
  stage: e2e_k8s
  rules:
    - when: on_success
  variables:
    E2E_MODE: "sequential"
    E2E_TAG: "e2e_sequential"
    E2E_TESTS: "./deploy/tests/e2e/cors:TestCorsSuite ./deploy/tests/e2e/crd-tcp:TestTCPSuite"
    K8S_VERSION: "v1.34.0"
  tags:
    - go
    - go-r1

"e2e_k8s:sequential-2":
  extends: .kind_deployment
  stage: e2e_k8s
  rules:
    - when: on_success
  variables:
    E2E_MODE: "sequential"
    E2E_TAG: "e2e_sequential"
    E2E_TESTS: "./deploy/tests/e2e/crd:TestGlobalSuite ./deploy/tests/e2e/tls-auth:TestTLSAuthSuite"
    K8S_VERSION: "v1.34.0"
  tags:
    - go
    - go-r2
`
	assert.Equal(t, expected, out)
}

func TestRenderFallsBackToThePlainGoTag(t *testing.T) {
	out, err := render(buildPipeline(twoShardJobSet(), fourTests(), nil))
	require.NoError(t, err)
	assert.NotContains(t, out, "go-r")
	assert.Equal(t, 2, strings.Count(out, "  tags:\n    - go\n"))
}

func TestRenderEmitsAllowFailure(t *testing.T) {
	jobs := twoShardJobSet()
	jobs[0].AllowFailure = true
	out, err := render(buildPipeline(jobs, fourTests(), []string{"go-r1"}))
	require.NoError(t, err)
	assert.Equal(t, 2, strings.Count(out, "  allow_failure: true\n"))
}

// TestRenderEmitsANoopJobWhenNothingIsSelected guards the child pipeline
// against being empty, which GitLab treats as a hard error.
func TestRenderEmitsANoopJobWhenNothingIsSelected(t *testing.T) {
	out, err := render(buildPipeline(nil, nil, nil))
	require.NoError(t, err)
	assert.Contains(t, out, "e2e-no-jobs:")
	assert.NotContains(t, out, ".kind_deployment")
}

// TestEveryGeneratedJobCarriesARule is the regression guard for the empty
// child pipeline: without an explicit rule GitLab applies the legacy
// only: [branches, tags] default and drops every job from an MR-ref pipeline.
func TestEveryGeneratedJobCarriesARule(t *testing.T) {
	for name, p := range map[string]childPipeline{
		"jobs":   buildPipeline(twoShardJobSet(), fourTests(), []string{"go-r1"}),
		"no-ops": buildPipeline(nil, nil, nil),
	} {
		out, err := render(p)
		require.NoError(t, err, name)

		parsed := map[string]any{}
		require.NoError(t, yaml.Unmarshal([]byte(out), &parsed), name)
		jobs := 0
		for key, value := range parsed {
			job, ok := value.(map[string]any)
			if !ok || strings.HasPrefix(key, ".") {
				continue
			}
			jobs++
			assert.NotNil(t, job["rules"], "%s: job %q has no rules", name, key)
		}
		assert.Positive(t, jobs, name)
	}
}

func TestRenderedPipelineIsValidYAML(t *testing.T) {
	out, err := render(buildPipeline(twoShardJobSet(), fourTests(), []string{"go-r1", "go-r2"}))
	require.NoError(t, err)

	parsed := map[string]any{}
	require.NoError(t, yaml.Unmarshal([]byte(out), &parsed))
	assert.Contains(t, parsed, "e2e_k8s:sequential-1")
	assert.Contains(t, parsed, "e2e_k8s:sequential-2")
	assert.Equal(t, []any{"e2e_k8s"}, parsed["stages"])
}

// TestParallelSplitKeepsOnePackageListSoGoTestRunsThemConcurrently is the
// guard for the parallel tag: splitting it per test would serialise packages
// that are meant to share a cluster at the same time.
func TestParallelSplitKeepsOnePackageListSoGoTestRunsThemConcurrently(t *testing.T) {
	jobs := []JobSet{{
		Name:   "e2e_k8s",
		Stage:  "e2e_k8s",
		Splits: []Split{{Tag: "e2e_parallel", Mode: "parallel", Shards: 1}},
	}}
	cases := []TestCase{
		{Tag: "e2e_parallel", Package: "./a", Name: "TestA"},
		{Tag: "e2e_parallel", Package: "./b", Name: "TestB"},
		{Tag: "e2e_parallel", Package: "./b", Name: "TestC"},
	}
	p := buildPipeline(jobs, cases, nil)
	require.Len(t, p.Legs, 1)

	got := map[string]string{}
	for _, v := range p.Legs[0].Variables {
		got[v.Name] = v.Value
	}
	assert.Equal(t, "parallel", got["E2E_MODE"])
	assert.Equal(t, "^(TestA|TestB|TestC)$", got["E2E_RUN"])
	assert.Equal(t, "./a ./b", got["E2E_PACKAGES"])
	assert.NotContains(t, got, "E2E_TESTS")
}

func TestDuplicateNamesFindsATestNameSharedByTwoPackages(t *testing.T) {
	cases := []TestCase{
		{Package: "./https", Name: "TestHTTPSSuite"},
		{Package: "./https-runtime", Name: "TestHTTPSSuite"},
		{Package: "./cors", Name: "TestCorsSuite"},
	}
	assert.Equal(t, []string{"TestHTTPSSuite"}, duplicateNames(cases))
	assert.Empty(t, duplicateNames(cases[1:]))
}
