// Copyright 2019 HAProxy Technologies LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
package main

import (
	"slices"
	"strings"
	"text/template"
)

// variable is one CI variable of a generated job, kept sorted for a stable render.
type variable struct {
	Name  string
	Value string
}

// leg is one generated job: a job set paired with a single test part.
type leg struct {
	Name         string
	Stage        string
	Tag          string
	Variables    []variable
	AllowFailure bool
}

// childPipeline is everything the template needs to render.
type childPipeline struct {
	Stages []string
	Legs   []leg
}

const pipelineTemplate = `# Generated by cmd/gitlab-e2e-jobs. Do not edit.
include:
  - local: .gitlab/variables.yml
  - local: .gitlab/.templates.yml

stages:
{{- range .Stages }}
  - {{ . }}
{{- end }}
{{ range .Legs }}
"{{ .Name }}":
  extends: .kind_deployment
  stage: {{ .Stage }}
  rules:
    - when: on_success
  needs:
    - pipeline: $PARENT_PIPELINE_ID
      job: docker-build
      artifacts: true
{{- if .AllowFailure }}
  allow_failure: true
{{- end }}
  variables:
{{- range .Variables }}
    {{ .Name }}: "{{ .Value }}"
{{- end }}
  tags:
    - go
{{- if .Tag }}
    - {{ .Tag }}
{{- end }}
{{ end }}`

const noJobsTemplate = `# Generated by cmd/gitlab-e2e-jobs. Do not edit.
include:
  - local: .gitlab/variables.yml

stages:
  - e2e-tests

e2e-no-jobs:
  stage: e2e-tests
  rules:
    - when: on_success
  image:
    name: $CI_REGISTRY_GO/golang:$GO_VERSION
    entrypoint: [""]
  tags:
    - go
  script:
    - echo "no e2e job set matches this pipeline"
`

// buildPipeline flattens job sets into one leg per test part and pins each leg.
func buildPipeline(jobs []JobSet, tags []string) childPipeline {
	legCount := 0
	for _, job := range jobs {
		legCount += len(job.Parts)
	}
	assigned := assignTags(legCount, tags)

	pipeline := childPipeline{
		Stages: make([]string, 0, len(jobs)),
		Legs:   make([]leg, 0, legCount),
	}
	index := 0
	for _, job := range jobs {
		if !slices.Contains(pipeline.Stages, job.Stage) {
			pipeline.Stages = append(pipeline.Stages, job.Stage)
		}
		for _, part := range job.Parts {
			pipeline.Legs = append(pipeline.Legs, leg{
				Name:         job.Name + ":" + part,
				Stage:        job.Stage,
				Tag:          assigned[index],
				Variables:    jobVariables(job, part),
				AllowFailure: job.AllowFailure,
			})
			index++
		}
	}
	return pipeline
}

// jobVariables merges the job set variables with TEST_PART, sorted by name.
func jobVariables(job JobSet, part string) []variable {
	variables := make([]variable, 0, len(job.Variables)+1)
	for name, value := range job.Variables {
		variables = append(variables, variable{Name: name, Value: value})
	}
	variables = append(variables, variable{Name: "TEST_PART", Value: part})
	slices.SortFunc(variables, func(a, b variable) int {
		return strings.Compare(a.Name, b.Name)
	})
	return variables
}

// render turns the pipeline into child pipeline YAML.
func render(p childPipeline) (string, error) {
	body := pipelineTemplate
	if len(p.Legs) == 0 {
		body = noJobsTemplate
	}
	parsed, err := template.New("pipeline").Parse(body)
	if err != nil {
		return "", err
	}
	out := &strings.Builder{}
	if err = parsed.Execute(out, p); err != nil {
		return "", err
	}
	return out.String(), nil
}
