// Copyright 2019 HAProxy Technologies LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
package main

import (
	"log"
	"slices"
	"strings"
	"text/template"
)

// variable is one CI variable of a generated job, kept sorted for a stable render.
type variable struct {
	Name  string
	Value string
}

// leg is one generated job: a job set paired with a single test part.
type leg struct {
	Name         string
	Stage        string
	Tag          string
	Variables    []variable
	AllowFailure bool
}

// childPipeline is everything the template needs to render.
type childPipeline struct {
	Stages []string
	Legs   []leg
}

const pipelineTemplate = `# Generated by cmd/gitlab-e2e-jobs. Do not edit.
include:
  - local: .gitlab/variables.yml
  - local: .gitlab/.templates.yml

stages:
{{- range .Stages }}
  - {{ . }}
{{- end }}
{{ range .Legs }}
"{{ .Name }}":
  extends: .kind_deployment
  stage: {{ .Stage }}
  rules:
    - when: on_success
  needs:
    - pipeline: $PARENT_PIPELINE_ID
      job: docker-build
      artifacts: true
{{- if .AllowFailure }}
  allow_failure: true
{{- end }}
  variables:
{{- range .Variables }}
    {{ .Name }}: "{{ .Value }}"
{{- end }}
  tags:
    - go
{{- if .Tag }}
    - {{ .Tag }}
{{- end }}
{{ end }}`

const noJobsTemplate = `# Generated by cmd/gitlab-e2e-jobs. Do not edit.
include:
  - local: .gitlab/variables.yml

stages:
  - e2e-tests

e2e-no-jobs:
  stage: e2e-tests
  rules:
    - when: on_success
  image:
    name: $CI_REGISTRY_GO/golang:$GO_VERSION
    entrypoint: [""]
  tags:
    - go
  script:
    - echo "no e2e job set matches this pipeline"
`

// buildPipeline turns each split shard into one job and pins it to a runner.
func buildPipeline(jobs []JobSet, tests []TestCase, tags []string) childPipeline {
	pipeline := childPipeline{
		Stages: make([]string, 0, len(jobs)),
		Legs:   make([]leg, 0, len(jobs)),
	}
	for _, job := range jobs {
		for _, split := range job.Splits {
			shards := shardTests(tests, split.Tag, split.Shards)
			if len(shards) == 0 {
				log.Printf("job %s: no test carries tag %s, skipping", job.Name, split.Tag)
				continue
			}
			if !slices.Contains(pipeline.Stages, job.Stage) {
				pipeline.Stages = append(pipeline.Stages, job.Stage)
			}
			for shard, cases := range shards {
				pipeline.Legs = append(pipeline.Legs, leg{
					Name:         job.Name + ":" + split.Label(shard, len(shards)),
					Stage:        job.Stage,
					Variables:    jobVariables(job, split, cases),
					AllowFailure: job.AllowFailure,
				})
			}
		}
	}
	for i, assigned := range assignTags(len(pipeline.Legs), tags) {
		pipeline.Legs[i].Tag = assigned
	}
	return pipeline
}

// testSpecs renders a shard as the package:test pairs the runner loops over.
func testSpecs(cases []TestCase) string {
	specs := make([]string, 0, len(cases))
	for _, test := range cases {
		specs = append(specs, test.Package+":"+test.Name)
	}
	return strings.Join(specs, " ")
}

// runRegex is the anchored -run expression selecting exactly the shard's tests.
func runRegex(cases []TestCase) string {
	names := make([]string, 0, len(cases))
	for _, test := range cases {
		if !slices.Contains(names, test.Name) {
			names = append(names, test.Name)
		}
	}
	return "^(" + strings.Join(names, "|") + ")$"
}

// shardPackages lists the shard's packages once each, in order.
func shardPackages(cases []TestCase) string {
	packages := make([]string, 0, len(cases))
	for _, test := range cases {
		if !slices.Contains(packages, test.Package) {
			packages = append(packages, test.Package)
		}
	}
	return strings.Join(packages, " ")
}

// duplicateNames reports test names that appear in more than one package of the
// same shard. A parallel shard shares one -run expression across its packages,
// so a repeated name would run the wrong test as well as the right one.
func duplicateNames(cases []TestCase) []string {
	packagesFor := map[string][]string{}
	for _, test := range cases {
		if !slices.Contains(packagesFor[test.Name], test.Package) {
			packagesFor[test.Name] = append(packagesFor[test.Name], test.Package)
		}
	}
	duplicates := []string{}
	for name, packages := range packagesFor {
		if len(packages) > 1 {
			duplicates = append(duplicates, name)
		}
	}
	slices.Sort(duplicates)
	return duplicates
}

// jobVariables merges the job set variables with what the shard needs to run,
// sorted by name.
func jobVariables(job JobSet, split Split, cases []TestCase) []variable {
	variables := make([]variable, 0, len(job.Variables)+4)
	for name, value := range job.Variables {
		variables = append(variables, variable{Name: name, Value: value})
	}
	variables = append(variables,
		variable{Name: "E2E_TAG", Value: split.Tag},
		variable{Name: "E2E_MODE", Value: split.RunMode()},
	)
	if split.RunMode() == modeSequential {
		variables = append(variables, variable{Name: "E2E_TESTS", Value: testSpecs(cases)})
	} else {
		variables = append(variables,
			variable{Name: "E2E_RUN", Value: runRegex(cases)},
			variable{Name: "E2E_PACKAGES", Value: shardPackages(cases)},
		)
	}
	slices.SortFunc(variables, func(a, b variable) int {
		return strings.Compare(a.Name, b.Name)
	})
	return variables
}

// render turns the pipeline into child pipeline YAML.
func render(p childPipeline) (string, error) {
	body := pipelineTemplate
	if len(p.Legs) == 0 {
		body = noJobsTemplate
	}
	parsed, err := template.New("pipeline").Parse(body)
	if err != nil {
		return "", err
	}
	out := &strings.Builder{}
	if err = parsed.Execute(out, p); err != nil {
		return "", err
	}
	return out.String(), nil
}
