// Copyright 2019 HAProxy Technologies LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
package main

import (
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"gopkg.in/yaml.v3"
)

func twoPartJobSet() []JobSet {
	return []JobSet{{
		Name:      "e2e_k8s",
		Stage:     "e2e_k8s",
		When:      "mr_or_push",
		Parts:     []string{"parallel", "https"},
		Variables: map[string]string{"K8S_VERSION": "v1.34.0"},
	}}
}

func TestBuildPipelineFansOutPartsAndAssignsTagsInOrder(t *testing.T) {
	p := buildPipeline(twoPartJobSet(), []string{"go-r1", "go-r2"})
	require.Len(t, p.Legs, 2)
	assert.Equal(t, []string{"e2e_k8s"}, p.Stages)
	assert.Equal(t, "e2e_k8s:parallel", p.Legs[0].Name)
	assert.Equal(t, "go-r1", p.Legs[0].Tag)
	assert.Equal(t, "e2e_k8s:https", p.Legs[1].Name)
	assert.Equal(t, "go-r2", p.Legs[1].Tag)
}

// TestBuildPipelineSortsVariablesForAStableRender keeps the generated YAML
// byte-identical between runs with the same inputs.
func TestBuildPipelineSortsVariablesForAStableRender(t *testing.T) {
	jobs := []JobSet{{
		Name:      "e2e_crd_v1",
		Stage:     "e2e_crd_versions",
		Parts:     []string{"parallel"},
		Variables: map[string]string{"KUBECTL": "v1.34.0", "CRD_VERSION": "v1", "K8S_VERSION": "v1.34.0"},
	}}
	p := buildPipeline(jobs, nil)
	require.Len(t, p.Legs, 1)
	assert.Equal(t, []variable{
		{Name: "CRD_VERSION", Value: "v1"},
		{Name: "K8S_VERSION", Value: "v1.34.0"},
		{Name: "KUBECTL", Value: "v1.34.0"},
		{Name: "TEST_PART", Value: "parallel"},
	}, p.Legs[0].Variables)
}

func TestRenderPinsEachLegToItsRunner(t *testing.T) {
	out, err := render(buildPipeline(twoPartJobSet(), []string{"go-r1", "go-r2"}))
	require.NoError(t, err)

	expected := `# Generated by cmd/gitlab-e2e-jobs. Do not edit.
include:
  - local: .gitlab/variables.yml
  - local: .gitlab/.templates.yml

stages:
  - e2e_k8s

"e2e_k8s:parallel":
  extends: .kind_deployment
  stage: e2e_k8s
  rules:
    - when: on_success
  needs:
    - pipeline: $PARENT_PIPELINE_ID
      job: docker-build
      artifacts: true
  variables:
    K8S_VERSION: "v1.34.0"
    TEST_PART: "parallel"
  tags:
    - go
    - go-r1

"e2e_k8s:https":
  extends: .kind_deployment
  stage: e2e_k8s
  rules:
    - when: on_success
  needs:
    - pipeline: $PARENT_PIPELINE_ID
      job: docker-build
      artifacts: true
  variables:
    K8S_VERSION: "v1.34.0"
    TEST_PART: "https"
  tags:
    - go
    - go-r2
`
	assert.Equal(t, expected, out)
}

func TestRenderFallsBackToThePlainGoTag(t *testing.T) {
	out, err := render(buildPipeline(twoPartJobSet(), nil))
	require.NoError(t, err)
	assert.NotContains(t, out, "go-r")
	assert.Equal(t, 2, strings.Count(out, "  tags:\n    - go\n"))
}

func TestRenderEmitsAllowFailure(t *testing.T) {
	jobs := []JobSet{{
		Name:         "e2e_crd_v1",
		Stage:        "e2e_crd_versions",
		Parts:        []string{"parallel"},
		AllowFailure: true,
		Variables:    map[string]string{"CRD_VERSION": "v1"},
	}}
	out, err := render(buildPipeline(jobs, []string{"go-r1"}))
	require.NoError(t, err)
	assert.Contains(t, out, "  allow_failure: true\n")
}

// TestRenderEmitsANoopJobWhenNothingIsSelected guards the child pipeline
// against being empty, which GitLab treats as a hard error.
func TestRenderEmitsANoopJobWhenNothingIsSelected(t *testing.T) {
	out, err := render(buildPipeline(nil, nil))
	require.NoError(t, err)
	assert.Contains(t, out, "e2e-no-jobs:")
	assert.NotContains(t, out, ".kind_deployment")
}

// TestEveryGeneratedJobCarriesARule is the regression guard for the empty
// child pipeline: without an explicit rule GitLab applies the legacy
// only: [branches, tags] default and drops every job from an MR-ref pipeline.
func TestEveryGeneratedJobCarriesARule(t *testing.T) {
	for name, p := range map[string]childPipeline{
		"jobs":   buildPipeline(twoPartJobSet(), []string{"go-r1"}),
		"no-ops": buildPipeline(nil, nil),
	} {
		out, err := render(p)
		require.NoError(t, err, name)

		parsed := map[string]any{}
		require.NoError(t, yaml.Unmarshal([]byte(out), &parsed), name)
		jobs := 0
		for key, value := range parsed {
			job, ok := value.(map[string]any)
			if !ok || strings.HasPrefix(key, ".") {
				continue
			}
			jobs++
			assert.NotNil(t, job["rules"], "%s: job %q has no rules", name, key)
		}
		assert.Positive(t, jobs, name)
	}
}

func TestRenderedPipelineIsValidYAML(t *testing.T) {
	out, err := render(buildPipeline(twoPartJobSet(), []string{"go-r1", "go-r2"}))
	require.NoError(t, err)

	parsed := map[string]any{}
	require.NoError(t, yaml.Unmarshal([]byte(out), &parsed))
	assert.Contains(t, parsed, "e2e_k8s:parallel")
	assert.Contains(t, parsed, "e2e_k8s:https")
	assert.Equal(t, []any{"e2e_k8s"}, parsed["stages"])
}
