.kind_deployment:
  stage: e2e-tests
  retry: 2
  needs: ["diff", "tidy", "docker-build"]
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: "$CI_PROJECT_NAMESPACE != 'haproxy-controller' && $CI_PIPELINE_SOURCE == 'push'"
    - if: $CI_PIPELINE_SOURCE == 'schedule'
  image: $CI_REGISTRY_GO/docker:$DOCKER_VERSION-go$GO_VERSION
  services:
    - name: $CI_REGISTRY_GO/docker:$DOCKER_VERSION-dind
      alias: docker
  tags:
    - go
  artifacts:
    paths:
      - tar
    expire_in: 1 minutes
    exclude:
      - tar/*
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY_GO
    - docker load -i tar/k8sIC.tar
    - go version
    - go mod download &
    #- docker pull -q $CI_REGISTRY_GO/alpine:3
    #- docker image tag $CI_REGISTRY_GO/alpine:3 alpine:3
    #- docker pull -q $CI_REGISTRY_GO/golang:$GO_VERSION-alpine
    #- docker image tag $CI_REGISTRY_GO/golang:$GO_VERSION-alpine golang:$GO_VERSION-alpine
    - docker pull -q $CI_REGISTRY_GO/haproxytech/http-echo:latest
    - docker image tag $CI_REGISTRY_GO/haproxytech/http-echo:latest haproxytech/http-echo:latest
    - docker pull -q $CI_REGISTRY_GO/haproxytech/proxy-protocol:latest
    - docker image tag $CI_REGISTRY_GO/haproxytech/proxy-protocol:latest haproxytech/proxy-protocol:latest
    - wget -nv -O /usr/local/bin/kind https://github.com/kubernetes-sigs/kind/releases/download/${KIND}/kind-linux-amd64
    - chmod +x /usr/local/bin/kind
    - wget -nv -O /usr/local/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/${KUBECTL}/bin/linux/amd64/kubectl
    - chmod +x /usr/local/bin/kubectl
    - sed -i "s/K8S_VERSION/$K8S_VERSION/g" ".gitlab/kind-config.yaml"
    - sed -i "s/KUBEADM_VER/$KUBEADM_VER/g" ".gitlab/kind-config.yaml"
    - sed -i "s~CI_REGISTRY_GO~$CI_REGISTRY_GO~g" ".gitlab/kind-config.yaml"
    - sed -i "s~FROM golang~FROM $CI_REGISTRY_GO/golang~g" "build/Dockerfile"
    - sed -i "s~FROM haproxytech/haproxy-alpine~FROM $CI_REGISTRY_GO/haproxy-alpine~g" "build/Dockerfile"
    - cat ./.gitlab/kind-config.yaml
    - kind create cluster --name=dev --config=./.gitlab/kind-config.yaml
    - sed -i -E -e "s/localhost|0\.0\.0\.0|127\.0\.0\.1/docker/g" "$HOME/.kube/config"
    - sed -i -E -e "s/localhost|0\.0\.0\.0|127\.0\.0\.1/docker/g" "deploy/tests/e2e/client.go"
    - until kubectl get nodes -o wide;do sleep 2; done
    - kubectl get pods -A
  after_script:
    - kubectl get pods -A
    - kind delete cluster --name=dev
  parallel:
    matrix:
      - TEST_PART: ["parallel", "https", "sequential-1", "sequential-2"]
  script:
    - gotest --version
    - CI_ENV=gitlab deploy/tests/create.sh
    - kubectl get pods -A
    - echo "running make -f Makefile.ci ci-e2e-$TEST_PART tests" && make -f Makefile.ci ci-e2e-$TEST_PART
.kind_deployment_schedules:
  extends: .kind_deployment
  allow_failure: true
