#!/bin/sh

MEMLIMIT=$(free -m | awk '/Mem:/ {print int($2 * 2 / 3)}')

CG_LIMIT_FILE="/sys/fs/cgroup/memory/memory.limit_in_bytes"
if [ -f "/sys/fs/cgroup/cgroup.controllers" ]; then
    CG_LIMIT_FILE="/sys/fs/cgroup/memory.max"
fi

if [ -r "${CG_LIMIT_FILE}" ]; then
    MEMLIMIT_CG=$(awk '{print int($1 / 1024 / 1024 * 2 / 3)}' "${CG_LIMIT_FILE}")

    if [ "${MEMLIMIT_CG}" -gt 0 ]; then
        if [ "${MEMLIMIT_CG}" -lt "${MEMLIMIT}" ]; then
            MEMLIMIT="${MEMLIMIT_CG}"
        fi
    fi
fi

echo "Memory limit for HAProxy: ${MEMLIMIT}MiB"

exec /usr/local/sbin/haproxy -W -db -m "${MEMLIMIT}" -S /var/run/haproxy-master.sock,level,admin -f /etc/haproxy/haproxy.cfg -f /etc/haproxy/haproxy-aux.cfg
