// Copyright 2019 HAProxy Technologies LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"fmt"
	"log"
	"strings"

	"github.com/google/renameio"
)

var title = `
# ![HAProxy](../assets/images/haproxy-weblogo-210x49.png "HAProxy")

## HAProxy kubernetes ingress controller `

var headerREADME = `

### Documentation

- [Controller options](controller.md)
- [Custom resource definitions](custom-resources.md)
- [Annotations](annotations.md)
- [Prometheus](prometheus.md)

### Lifecycle

- [Lifecycle](lifecycle.md)

#### Experimental
- [Gateway API](gateway-api.md)

#### Additional
- [Supervisor](gopherd.md)

This is autogenerated from [doc.yaml](doc.yaml). Description can be found in [generator readme](gen/README.md)

`

func (c *Conf) generateReadme() {
	var buff strings.Builder
	buff.WriteString(title)
	buff.WriteString(c.ActiveVersion.String())
	buff.WriteString(headerREADME)

	err := renameio.WriteFile("../../documentation/README.md", []byte(buff.String()), 0o644)
	if err != nil {
		log.Println(err)
	}
}

func selectExamples(ann *ConfItem, buff *strings.Builder) {
	numOverrides := 0
	numApplies := len(ann.AppliesTo)
	if ann.Title == "syslog-server" {
		numOverrides = 0
	}
	if ann.ExampleConfigmap != "" {
		numOverrides++
	}
	if ann.ExampleIngress != "" {
		numOverrides++
	}
	if ann.ExampleService != "" {
		numOverrides++
	}
	if numOverrides == 0 || numOverrides == 1 && numApplies == 1 {
		if ContainsB(ann.AppliesTo, "configmap") {
			buff.WriteString("Example:\n\n```yaml\n")
			if ann.ExampleConfigmap == "" {
				buff.WriteString(strings.Join(ann.Example, "\n"))
			} else {
				buff.WriteString(ann.ExampleConfigmap)
			}
			buff.WriteString("\n```\n\n")
		} else {
			buff.WriteString("Example:\n\n```yaml\n")
			for _, line := range ann.Example {
				if line[0] != '#' && ann.Title != "ingress.class" {
					buff.WriteString("haproxy.org/")
				}
				buff.WriteString(line)
				buff.WriteString("\n")
			}
			buff.WriteString("\n```\n\n")
		}
		return
	}

	if ann.ExampleConfigmap != "" {
		buff.WriteString("Example (configmap):\n\n```yaml\n")
		buff.WriteString(ann.ExampleConfigmap)
		buff.WriteString("\n```\n\n")
	}
	if ann.ExampleIngress != "" && ann.ExampleIngress == ann.ExampleService {
		buff.WriteString("Example (ingress, service):\n\n```yaml\n")
		buff.WriteString(ann.ExampleIngress)
		buff.WriteString("\n```\n\n")
	} else {
		if ann.ExampleIngress != "" {
			buff.WriteString("Example (ingress):\n\n```yaml\n")
			buff.WriteString(ann.ExampleIngress)
			buff.WriteString("\n```\n\n")
		}
		if ann.ExampleService != "" {
			buff.WriteString("Example (service):\n\n```yaml\n")
			buff.WriteString(ann.ExampleService)
			buff.WriteString("\n```\n\n")
		}
	}
}

func writeValue(value, defaultValue string) string {
	if value != defaultValue {
		return value
	}
	return value + " `default`"
}

// writeRelatedDocs renders the optional related_docs field of doc.yaml as a
// "Related documentation" list, so links to side documents stay structured
// instead of being inlined in descriptions.
func writeRelatedDocs(docs []string, buff *strings.Builder) {
	if len(docs) == 0 {
		return
	}
	buff.WriteString("Related documentation:\n\n")
	for _, doc := range docs {
		name := strings.TrimPrefix(doc, "./")
		buff.WriteString(fmt.Sprintf("- [%s](%s)\n", name, doc))
	}
	buff.WriteString("\n")
}
