#!/command/with-contenv sh

MEMLIMIT=$(free -m | awk '/Mem:/ {printf "%d\n", int($2 * 2 / 3)}')

CG_LIMIT_FILE="/sys/fs/cgroup/memory/memory.limit_in_bytes"
if [ -f "/sys/fs/cgroup/cgroup.controllers" ]; then
    CG_LIMIT_FILE="/sys/fs/cgroup/memory.max"
fi

if [ -r "${CG_LIMIT_FILE}" ]; then
    if grep -q '^max$' "${CG_LIMIT_FILE}"; then
        MEMLIMIT_CG="${MEMLIMIT}"
    else
        MEMLIMIT_CG=$(awk '{printf "%d\n", int($1 / 1024 / 1024 * 2 / 3)}' "${CG_LIMIT_FILE}")
    fi

    if [ "${MEMLIMIT_CG}" -gt 0 ]; then
        if [ "${MEMLIMIT_CG}" -lt "${MEMLIMIT}" ]; then
            MEMLIMIT="${MEMLIMIT_CG}"
        fi
    fi
fi

echo "Memory limit for HAProxy: ${MEMLIMIT}MiB"
export LD_PRELOAD=/usr/local/lib/libblock_secrets.so

# if master socket is changed, that needs to be aligned in pkg/haproxy/process/interface.go
exec /usr/local/sbin/haproxy -W -db -m "${MEMLIMIT}" -S /var/run/haproxy-master.sock,level,admin -f /etc/haproxy/haproxy.cfg -f /etc/haproxy/haproxy-aux.cfg
