name: Generated documentation
on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set the expected Go version
        run: |
          GOMOD_VERSION=$(cat go.mod | grep -i "^go " | sed -e "s/go //g")
          echo "GOMOD_VERSION=${GOMOD_VERSION}" >> $GITHUB_ENV
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "${{ env.GOMOD_VERSION }}"
      - name: generating documentation
        run: cd documentation/gen && go run .
      - name: changes
        run: test -z "$(git diff 2> /dev/null)" || exit "Documentation is not generated, issue \`cd documentation/gen && go run .\` and commit the result"
      - name: untracked files
        run: test -z "$(git ls-files --others --exclude-standard 2> /dev/null)" || exit "Documentation created untracked files, cannot proceed"
