name: Linting
on: [push, pull_request]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 10
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2.2.0
        with:
          version: v1.28
          args: --timeout 2m
